# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer\ui\calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys

class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(361, 588)
        self.centralwidget = QtWidgets.QWidget(Calculator)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 140, 341, 411))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.percentage_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.press_it("%"))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.percentage_button.setFont(font)
        self.percentage_button.setObjectName("percentage_button")
        self.gridLayout.addWidget(self.percentage_button, 0, 0, 1, 1)
        self.clrear_all_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.press_it("C"))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.clrear_all_button.setFont(font)
        self.clrear_all_button.setObjectName("clrear_all_button")
        self.gridLayout.addWidget(self.clrear_all_button, 0, 1, 1, 1)
        self.arrow_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.back_button())
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.arrow_button.setFont(font)
        self.arrow_button.setObjectName("arrow_button")
        self.gridLayout.addWidget(self.arrow_button, 0, 2, 1, 1)
        self.divide_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.press_it("/"))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.divide_button.setFont(font)
        self.divide_button.setObjectName("divide_button")
        self.gridLayout.addWidget(self.divide_button, 0, 3, 1, 1)
        self.seven_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.press_it("7"))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.seven_button.setFont(font)
        self.seven_button.setObjectName("seven_button")
        self.gridLayout.addWidget(self.seven_button, 1, 0, 1, 1)
        self.eight_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.press_it("8"))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.eight_button.setFont(font)
        self.eight_button.setObjectName("eight_button")
        self.gridLayout.addWidget(self.eight_button, 1, 1, 1, 1)
        self.nine_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.press_it("9"))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.nine_button.setFont(font)
        self.nine_button.setObjectName("nine_button")
        self.gridLayout.addWidget(self.nine_button, 1, 2, 1, 1)
        self.multiply_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.press_it("*"))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.multiply_button.setFont(font)
        self.multiply_button.setObjectName("multiply_button")
        self.gridLayout.addWidget(self.multiply_button, 1, 3, 1, 1)
        self.four_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.press_it("4"))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.four_button.setFont(font)
        self.four_button.setObjectName("four_button")
        self.gridLayout.addWidget(self.four_button, 2, 0, 1, 1)
        self.five_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.press_it("5"))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.five_button.setFont(font)
        self.five_button.setObjectName("five_button")
        self.gridLayout.addWidget(self.five_button, 2, 1, 1, 1)
        self.six_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.press_it("6"))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.six_button.setFont(font)
        self.six_button.setObjectName("six_button")
        self.gridLayout.addWidget(self.six_button, 2, 2, 1, 1)
        self.minus_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.press_it("-"))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.minus_button.setFont(font)
        self.minus_button.setObjectName("minus_button")
        self.gridLayout.addWidget(self.minus_button, 2, 3, 1, 1)
        self.one_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.press_it("1"))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.one_button.setFont(font)
        self.one_button.setObjectName("one_button")
        self.gridLayout.addWidget(self.one_button, 3, 0, 1, 1)
        self.two_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.press_it("2"))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.two_button.setFont(font)
        self.two_button.setObjectName("two_button")
        self.gridLayout.addWidget(self.two_button, 3, 1, 1, 1)
        self.three_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.press_it("3"))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.three_button.setFont(font)
        self.three_button.setObjectName("three_button")
        self.gridLayout.addWidget(self.three_button, 3, 2, 1, 1)
        self.pluse_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.press_it("+"))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.pluse_button.setFont(font)
        self.pluse_button.setObjectName("pluse_button")
        self.gridLayout.addWidget(self.pluse_button, 3, 3, 1, 1)
        self.plus_minus_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.add_plus_minus())
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.plus_minus_button.setFont(font)
        self.plus_minus_button.setObjectName("plus_minus_button")
        self.gridLayout.addWidget(self.plus_minus_button, 4, 0, 1, 1)
        self.zero_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.press_it("0"))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.zero_button.setFont(font)
        self.zero_button.setObjectName("zero_button")
        self.gridLayout.addWidget(self.zero_button, 4, 1, 1, 1)
        self.point_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.dot_it())
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.point_button.setFont(font)
        self.point_button.setObjectName("point_button")
        self.gridLayout.addWidget(self.point_button, 4, 2, 1, 1)
        self.equelto_button = QtWidgets.QPushButton(self.widget, clicked = lambda: self.equel_to_button())
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.equelto_button.setFont(font)
        self.equelto_button.setObjectName("equelto_button")
        self.gridLayout.addWidget(self.equelto_button, 4, 3, 1, 1)
        Calculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Calculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 27))
        self.menubar.setObjectName("menubar")
        Calculator.setMenuBar(self.menubar)

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    # Managed the dot (.) functionality
    def dot_it(self):
        seceen = self.label_2.text()
        if seceen[-1] == ".":     #  { seceen[-1] } -> it take the last item of the string
            pass 
        else:
            self.label_2.setText(f"{seceen}.")

    # Handle The back button
    def back_button(self): 
        seceen = self.label_2.text()
        seceen = seceen[:-1]
        self.label_2.setText(f"{seceen}")

    # Remove Last Charactor from screen 
    def press_it(self, pressed):
        if pressed == "C":
            self.label_2.setText("0")
        else:
            # When value is the Zero the it should be clear
            if self.label_2.text() == "0":
                self.label_2.setText("")
            # Concatinate the presed button with what was there already
            self.label_2.setText(f"{self.label_2.text()}{pressed}")

    # change the positive and nagetive
    def add_plus_minus(self):
        screen = self.label_2.text()
        if screen == "":
            pass
        elif "-" in screen:
            self.label_2.setText(screen.replace("-", ""))
        else:
            self.label_2.setText(f"-{screen}")
    
    # Equel to Button
    def equel_to_button(self):
        screen = self.label_2.text()
        if screen == "":
            pass
        else:
            try:
                answer = eval(screen)
                self.label_2.setText(str(answer))
            except:
                self.label_2.setText("ERROR")


    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "MainWindow"))
        self.label_2.setText(_translate("Calculator", "0"))
        self.percentage_button.setText(_translate("Calculator", "%"))
        self.clrear_all_button.setText(_translate("Calculator", "C"))
        self.arrow_button.setText(_translate("Calculator", "<<"))
        self.divide_button.setText(_translate("Calculator", "/"))
        self.seven_button.setText(_translate("Calculator", "7"))
        self.eight_button.setText(_translate("Calculator", "8"))
        self.nine_button.setText(_translate("Calculator", "9"))
        self.multiply_button.setText(_translate("Calculator", "X"))
        self.four_button.setText(_translate("Calculator", "4"))
        self.five_button.setText(_translate("Calculator", "5"))
        self.six_button.setText(_translate("Calculator", "6"))
        self.minus_button.setText(_translate("Calculator", "-"))
        self.one_button.setText(_translate("Calculator", "1"))
        self.two_button.setText(_translate("Calculator", "2"))
        self.three_button.setText(_translate("Calculator", "3"))
        self.pluse_button.setText(_translate("Calculator", "+"))
        self.plus_minus_button.setText(_translate("Calculator", "+/-"))
        self.zero_button.setText(_translate("Calculator", "0"))
        self.point_button.setText(_translate("Calculator", "."))
        self.equelto_button.setText(_translate("Calculator", "="))


def window():
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_Calculator()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

window()



# , clicked = lambda: self.press_it()