# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer\ui\open_file_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QFileDialog
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.main_window = MainWindow  # ✅ Store reference -> this IMP Line
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 379)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 190, 511, 51))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 50, 341, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.clicked.connect(self.open_file_manager)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 664, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Open the File by clicking the button
    def open_file_manager(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog

        # ✅ Use self.main_window instead of self
        file_path, _ = QFileDialog.getOpenFileName(
            self.main_window,
            "Select a file",
            "",
            "All Files (*);;Text Files (*.txt)",
            options=options
        )

        if file_path:
            self.label.setText(file_path)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "File Path"))
        self.pushButton.setText(_translate("MainWindow", "Open File"))


def window():
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

window()








        # # self.label.setText("You have cliked the button!")
        # # Open the file dialog
        # f_name = QFileDialog.getOpenFileName(self, "Open File", "", "All Files (*);;Python Files (*.py)")

        # # Output file name to screen 
        # if f_name:
        #     self.label.setText(str(f_name))