# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer\ui\to_do_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(528, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 10, 491, 81))
        self.lineEdit.setObjectName("lineEdit")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 160, 491, 301))
        self.listWidget.setObjectName("listWidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 110, 491, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)

        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_item_btn = QtWidgets.QPushButton(self.widget)
        self.add_item_btn.clicked.connect(self.add_it)
        self.add_item_btn.setObjectName("add_item_btn")

        self.horizontalLayout.addWidget(self.add_item_btn)
        self.delete_item_btn = QtWidgets.QPushButton(self.widget)
        self.delete_item_btn.clicked.connect(self.delete_it)
        self.delete_item_btn.setObjectName("delete_item_btn")

        self.horizontalLayout.addWidget(self.delete_item_btn)
        self.clear_the_list = QtWidgets.QPushButton(self.widget)
        self.clear_the_list.clicked.connect(self.clear_it)
        self.clear_the_list.setObjectName("clear_the_list")

        self.horizontalLayout.addWidget(self.clear_the_list)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 528, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Add Item to List 
    def add_it(self):
        # Grab Item From 
        item = self.lineEdit.text()
        # Add Item to List
        self.listWidget.addItem(item)
        # Clear the Item Box
        self.lineEdit.setText("")

    # Delete Item to List
    def delete_it(self):
        # Grab the selected row and current row
        clicked = self.listWidget.currentRow()
        # Take Item's from List
        self.listWidget.takeItem(clicked)

    # Add Clear to List
    def clear_it(self):
        self.listWidget.clear()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_item_btn.setText(_translate("MainWindow", "Add Item To List"))
        self.delete_item_btn.setText(_translate("MainWindow", "Delete Item From List"))
        self.clear_the_list.setText(_translate("MainWindow", "Clear The List"))



def window():
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

window()