# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer\ui\window_navigation\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
from window_2 import Ui_SecondWindow
import sys


class Ui_MainWindow(object):
    def openSecondWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SecondWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, window_one):
        window_one.setObjectName("window_one")
        window_one.resize(575, 247)
        font = QtGui.QFont()
        font.setPointSize(18)
        window_one.setFont(font)
        self.centralwidget = QtWidgets.QWidget(window_one)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 40, 231, 81))
        self.pushButton.clicked.connect(self.openSecondWindow)
        self.pushButton.setObjectName("pushButton")
        window_one.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window_one)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 47))
        self.menubar.setObjectName("menubar")
        window_one.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window_one)
        self.statusbar.setObjectName("statusbar")
        window_one.setStatusBar(self.statusbar)

        self.retranslateUi(window_one)
        QtCore.QMetaObject.connectSlotsByName(window_one)

    def retranslateUi(self, window_one):
        _translate = QtCore.QCoreApplication.translate
        window_one.setWindowTitle(_translate("window_one", "MainWindow"))
        self.pushButton.setText(_translate("window_one", "Open Window"))


def window():
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

window()
